"use client";

import { useEffect, useMemo } from "react";
import { useFunds } from "@/lib/useFunds";
import { useFilterStore, filterFunds } from "@/store/useFilterStore";
import { buildProjection } from "@/lib/model";
import { MethodologySelector } from "@/components/MethodologySelector";
import { MetricsGrid } from "@/components/MetricsGrid";
import { FilterBar } from "@/components/FilterBar";
import { JCurveChart } from "@/components/JCurveChart";
import { CashFlowTable } from "@/components/CashFlowTable";
import { FundExplorer } from "@/components/FundExplorer";
import { METHODOLOGIES } from "@/lib/types";

export default function Home() {
  const { funds, loading } = useFunds();
  const filters = useFilterStore();
  const initBounds = useFilterStore((s) => s.initBounds);

  useEffect(() => {
    if (funds.length > 0) initBounds(funds);
  }, [funds, initBounds]);

  const filtered = useMemo(() => filterFunds(funds, filters), [funds, filters]);
  const projection = useMemo(
    () => buildProjection(filtered, filters.methodology),
    [filtered, filters.methodology]
  );

  const methodologyLabel = METHODOLOGIES.find((m) => m.id === filters.methodology)?.label;

  return (
    <div className="min-h-full bg-neutral-950 text-neutral-100">
      <header className="border-b border-neutral-800 bg-neutral-950 sticky top-0 z-30">
        <div className="mx-auto max-w-[1400px] px-4 py-3 flex items-center justify-between gap-4">
          <div>
            <h1 className="text-lg font-semibold tracking-tight">Fund J-Curve Analytics</h1>
            <p className="text-xs text-neutral-500">
              Real fund identity from the SEC Form D pipeline · modeled capital-call, distribution &amp; NAV
              projections
            </p>
          </div>
          <div className="text-right text-xs text-neutral-500 hidden sm:block">
            {loading ? (
              "Loading fund data..."
            ) : (
              <>
                {funds.length.toLocaleString()} funds loaded
                <br />
                Vintages {filters.bounds.vintageMin}–{filters.bounds.vintageMax}
              </>
            )}
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-[1400px] px-4 py-5 flex flex-col gap-5">
        {loading ? (
          <div className="flex items-center justify-center py-32 text-neutral-500 text-sm">
            Loading fund dataset (~37K funds)...
          </div>
        ) : (
          <>
            <MethodologySelector />

            <div>
              <h2 className="text-sm font-semibold text-neutral-300 uppercase tracking-wide mb-2">
                Portfolio Summary — {methodologyLabel}
              </h2>
              <MetricsGrid metrics={projection.metrics} />
            </div>

            <FilterBar />

            <div>
              <h2 className="text-sm font-semibold text-neutral-300 uppercase tracking-wide mb-2">
                Interactive J-Curve
              </h2>
              <JCurveChart points={projection.points} />
            </div>

            <div>
              <h2 className="text-sm font-semibold text-neutral-300 uppercase tracking-wide mb-2">
                Annual Cash Flow Projection
              </h2>
              <CashFlowTable points={projection.points} committedCapital={projection.metrics.committedCapital} />
            </div>

            <FundExplorer funds={filtered} />

            <footer className="text-[11px] text-neutral-600 border-t border-neutral-800 pt-3 pb-6 leading-relaxed">
              Fund identity (name, manager, fund type, vintage, committed capital, structure, domicile) is sourced
              from SEC Form D pooled-offering filings (Jan 2025 – Jun 2026 filing window), the same pipeline used by
              the Open Disclosure app. Form D reports issuer-side offering data only — it contains no capital-call,
              distribution, or NAV history for any fund. All cash-flow, NAV, and return projections shown here are
              generated by the selected methodology&apos;s model from type-level assumptions and are illustrative,
              not historical performance.
            </footer>
          </>
        )}
      </main>
    </div>
  );
}
