export function Disclosure() {
  return (
    <footer className="border-t border-neutral-800 pt-4 pb-8 text-[11px] leading-relaxed text-neutral-600">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-neutral-500 mb-2">Disclosure</h2>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-8 gap-y-3 max-w-5xl">
        <p>
          <strong className="text-neutral-500">Not investment advice.</strong> This tool is provided for
          informational and illustrative purposes only. Nothing on this page is an offer to sell, or a solicitation
          of an offer to buy, any security or fund interest, and none of it constitutes investment, legal, tax, or
          accounting advice. Consult a licensed financial, tax, or legal advisor before making any investment
          decision.
        </p>
        <p>
          <strong className="text-neutral-500">What&apos;s real vs. modeled.</strong> Fund name, manager, fund type,
          vintage year, committed capital, entity structure, and domicile are sourced from SEC Form D pooled-offering
          filings, 2020–2026. Form D reports issuer-side offering data only — it contains no capital-call,
          distribution, or NAV history for any fund. Every capital-call, distribution, NAV, and return figure shown
          is generated by the selected methodology&apos;s model from type-level assumptions (rate of contribution,
          growth, yield, bow factor, etc.), not from actual fund performance records.
        </p>
        <p>
          <strong className="text-neutral-500">Two data sources, two conventions.</strong> Vintages 2025–2026 come
          from the Open Disclosure app&apos;s pipeline, which resolves each fund&apos;s amendment history to its
          latest known filing state. Vintages 2020–2024 were backfilled directly from SEC&apos;s quarterly Form D
          archives (
          <code className="text-neutral-500">scripts/formd_browser_extractor.js</code>) and use only each
          fund&apos;s original (&quot;D&quot;) filing, not later amendments — committed capital for those vintages
          reflects the amount at initial filing. SEC EDGAR blocks automated bulk downloads with anything but a real
          browser session, which is why this required a browser-based extractor rather than the usual scripted pull.
        </p>
        <p>
          <strong className="text-neutral-500">Feeder funds and cross-window duplicates removed.</strong> Feeder
          funds pass capital straight into a master fund rather than running their own strategy, so a feeder&apos;s
          cash flows are just a copy of its master&apos;s — counting both double-counts the same pool of capital
          under two names (verified: &quot;Jetha Global Master Fund&quot; at $40M plus its two named feeders summed
          to ~$82M for what is one $40M pool). Feeder-named filings are dropped; masters are kept. Separately, a
          fund that filed in the 2020–2024 backfill and later amended in the 2025–2026 window previously appeared
          twice, once from each source (verified: &quot;Graham Global Investment Fund II SPC Ltd&quot; at $14.0B
          and $17.0B) — exact-name matches across that boundary now keep only the more recent entry.
        </p>
        <p>
          <strong className="text-neutral-500">Parallel vehicles consolidated.</strong> Funds are often split into
          parallel vehicles by investor type or tax residency — &quot;Fund VI&quot; / &quot;Fund VI-A&quot; /
          &quot;Fund VI-B&quot;, or &quot;Fund (Onshore)&quot; / &quot;Fund (Offshore)&quot; — each with its own Form
          D. When every vehicle in a family reports the exact same committed-capital figure, that&apos;s the whole
          fund&apos;s target repeated on each filing, not that amount raised several times over (verified:
          &quot;FRANCISCO PARTNERS VI, L.P.&quot; plus its -A/-B/-C/-D vehicles all reported an identical $6.6B
          target across 5 filings, not $33B; &quot;EagleTree Partners VI (Offshore), LP&quot; and its Onshore
          counterpart both reported an identical $1.6B). Only that unambiguous case is consolidated to one entry;
          families where vehicles report genuinely different amounts (e.g. D1 Capital Partners&apos; Onshore vehicle
          at $7.2B vs. its Offshore vehicle at $4.5B — plausibly distinct, additive sub-commitments) are left as-is.
        </p>
        <p>
          <strong className="text-neutral-500">&quot;Filings,&quot; not a deduplicated fund count.</strong> The
          fund count shown is Form D pooled-fund <em>offering filings</em> from 2020–2026, not a count of distinct
          private funds — it is not directly comparable to SEC&apos;s own published{" "}
          <a
            href="https://www.sec.gov/data-research/statistics-data-visualizations/private-fund-statistics"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-neutral-400"
          >
            Private Fund Statistics
          </a>{" "}
          (54,392 funds at large advisers, Form PF, 2025Q3; ~108,752 funds across all RIA/ERA-advised funds, Form
          ADV, most recent snapshot). Those are deduplicated snapshots of currently active funds; this dataset is a
          filing-event count over a fixed window. Feeders, cross-window duplicates, and same-amount parallel
          vehicles are removed (see above), but a fund can still file separate Form Ds for parallel vehicles that
          report genuinely different amounts, and Form D itself requires no SEC-registered adviser at all — both
          still push this count above a true distinct-fund total, while excluding funds with no new or amended
          filing since 2020 pulls it back down.
        </p>
        <p>
          <strong className="text-neutral-500">No guarantee of accuracy.</strong> Data is provided &quot;as is&quot;
          from public SEC filings and may contain filer errors, omissions, or reporting anomalies (a small number of
          extreme outliers were excluded during cleaning — see{" "}
          <code className="text-neutral-500">scripts/export_funds.py</code>). Modeled projections rely on simplified
          assumptions and simulated randomness; actual fund cash flows, NAV, and returns will differ, often
          materially, from any figure shown here. Past or projected performance is not indicative of future results.
        </p>
        <p>
          <strong className="text-neutral-500">PME / Direct Alpha.</strong> The Public Market Equivalent and Direct
          Alpha figures benchmark modeled cash flows against a hypothetical index compounding at a constant,
          user-set annual rate — not a real historical index feed (e.g. actual S&amp;P 500 daily returns). Treat
          them as an illustration of the comparison method, not a live benchmark.
        </p>
        <p className="lg:col-span-2 text-neutral-700">
          Not affiliated with, endorsed by, or a service of the U.S. Securities and Exchange Commission. Fund names
          and manager names are drawn from public regulatory filings and are shown for identification purposes only.
        </p>
      </div>
    </footer>
  );
}
