export function Disclosure() {
  return (
    <footer className="border-t border-neutral-800 pt-4 pb-8 text-[11px] leading-relaxed text-neutral-600">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-neutral-500 mb-2">Disclosure</h2>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-8 gap-y-3 max-w-5xl">
        <p>
          <strong className="text-neutral-500">Not investment advice.</strong> This tool is provided for
          informational and illustrative purposes only. Nothing on this page is an offer to sell, or a solicitation
          of an offer to buy, any security or fund interest, and none of it constitutes investment, legal, tax, or
          accounting advice. Consult a licensed financial, tax, or legal advisor before making any investment
          decision.
        </p>
        <p>
          <strong className="text-neutral-500">What&apos;s real vs. modeled.</strong> Fund name, manager, fund type,
          vintage year, committed capital, entity structure, and domicile are sourced from SEC Form D pooled-offering
          filings covering the Jan 2025 – Jun 2026 filing window, the same pipeline used by the Open Disclosure app.
          Form D reports issuer-side offering data only — it contains no capital-call, distribution, or NAV history
          for any fund. Every capital-call, distribution, NAV, and return figure shown is generated by the selected
          methodology&apos;s model from type-level assumptions (rate of contribution, growth, yield, bow factor,
          etc.), not from actual fund performance records.
        </p>
        <p>
          <strong className="text-neutral-500">Vintage coverage is limited by the source data.</strong> Only
          vintages 2025–2026 appear because the underlying Form D dataset currently loaded spans six quarters
          (Jan 2025 – Jun 2026) — SEC EDGAR blocks automated bulk downloads of older structured-data archives, so
          earlier quarters require a manual pull into the source pipeline. A fund&apos;s &quot;vintage&quot; here is
          the year of its earliest filing found within that window, which may postdate its true formation date for
          funds that filed amendments before the window began.
        </p>
        <p>
          <strong className="text-neutral-500">No guarantee of accuracy.</strong> Data is provided &quot;as is&quot;
          from public SEC filings and may contain filer errors, omissions, or reporting anomalies (a small number of
          extreme outliers were excluded during cleaning — see{" "}
          <code className="text-neutral-500">scripts/export_funds.py</code>). Modeled projections rely on simplified
          assumptions and simulated randomness; actual fund cash flows, NAV, and returns will differ, often
          materially, from any figure shown here. Past or projected performance is not indicative of future results.
        </p>
        <p className="lg:col-span-2 text-neutral-700">
          Not affiliated with, endorsed by, or a service of the U.S. Securities and Exchange Commission. Fund names
          and manager names are drawn from public regulatory filings and are shown for identification purposes only.
        </p>
      </div>
    </footer>
  );
}
