export function Disclosure() {
  return (
    <footer className="border-t border-neutral-800 pt-4 pb-8 text-[11px] leading-relaxed text-neutral-600">
      <h2 className="text-xs font-semibold uppercase tracking-wide text-neutral-500 mb-2">Disclosure</h2>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-x-8 gap-y-3 max-w-5xl">
        <p>
          <strong className="text-neutral-500">Not investment advice.</strong> This tool is provided for
          informational and illustrative purposes only. Nothing on this page is an offer to sell, or a solicitation
          of an offer to buy, any security or fund interest, and none of it constitutes investment, legal, tax, or
          accounting advice. Consult a licensed financial, tax, or legal advisor before making any investment
          decision.
        </p>
        <p>
          <strong className="text-neutral-500">What&apos;s real vs. modeled.</strong> Fund name, manager, fund type,
          vintage year, committed capital, entity structure, and domicile are sourced from SEC Form D pooled-offering
          filings, 2020–2026. Form D reports issuer-side offering data only — it contains no capital-call,
          distribution, or NAV history for any fund. Every capital-call, distribution, NAV, and return figure shown
          is generated by the selected methodology&apos;s model from type-level assumptions (rate of contribution,
          growth, yield, bow factor, etc.), not from actual fund performance records.
        </p>
        <p>
          <strong className="text-neutral-500">Two data sources, two conventions.</strong> Vintages 2025–2026 come
          from the Open Disclosure app&apos;s pipeline, which resolves each fund&apos;s amendment history to its
          latest known filing state. Vintages 2020–2024 were backfilled directly from SEC&apos;s quarterly Form D
          archives (
          <code className="text-neutral-500">scripts/formd_browser_extractor.js</code>) and use only each
          fund&apos;s original (&quot;D&quot;) filing, not later amendments — committed capital for those vintages
          reflects the amount at initial filing. SEC EDGAR blocks automated bulk downloads with anything but a real
          browser session, which is why this required a browser-based extractor rather than the usual scripted pull.
        </p>
        <p>
          <strong className="text-neutral-500">No guarantee of accuracy.</strong> Data is provided &quot;as is&quot;
          from public SEC filings and may contain filer errors, omissions, or reporting anomalies (a small number of
          extreme outliers were excluded during cleaning — see{" "}
          <code className="text-neutral-500">scripts/export_funds.py</code>). Modeled projections rely on simplified
          assumptions and simulated randomness; actual fund cash flows, NAV, and returns will differ, often
          materially, from any figure shown here. Past or projected performance is not indicative of future results.
        </p>
        <p>
          <strong className="text-neutral-500">PME / Direct Alpha.</strong> The Public Market Equivalent and Direct
          Alpha figures benchmark modeled cash flows against a hypothetical index compounding at a constant,
          user-set annual rate — not a real historical index feed (e.g. actual S&amp;P 500 daily returns). Treat
          them as an illustration of the comparison method, not a live benchmark.
        </p>
        <p className="text-neutral-700">
          Not affiliated with, endorsed by, or a service of the U.S. Securities and Exchange Commission. Fund names
          and manager names are drawn from public regulatory filings and are shown for identification purposes only.
        </p>
      </div>
    </footer>
  );
}
